<?php
return [
  "home_title" => "Sustainable Wood Pellet Exporter From Indonesia",
  "home_sub" => "Delivering responsibly sourced biomass fuel to global markets.",
  "about_title" => "About Us",
  "about_text" => "<p><b>PT Archipelago Jaya Nusantara</b> is a company engaged in various sectors, including biomass energy.</p><br>Our vision is to support the global shift toward more environmentally friendly energy sources by providing high-quality products such as wood pellets. As an international wood pellet exporter, we are committed to helping buyers obtain the products they need through clear, fast, and efficient communication. We believe that strong business relationships are built on trust, transparency, and professionalism.",
  "about_text_2" => "<p>Driven by sustainability and innovation, PT Archipelago Jaya Nusantara aims to be a trusted partner in providing green energy for a cleaner and more sustainable world.</p>",
  "products_title" => "Our Products",
  "sustainability_title" => "Sustainability",
  "contact_title" => "Contact",
  "get_quote" => "Get Quote",
  "explore_products" => "Explore Products",
  "name_placeholder" => "Your full name",
  "email_placeholder" => "Your email address",
  "phone_placeholder" => "Your phone number",
  "message_placeholder" => "Your message",
  "quote_name_placeholder" => "Your full name",
  "quote_email_placeholder" => "Your email address",
  "quote_company_placeholder" => "Your company name",
  "quote_product_placeholder" => "Product you are interested in",
  "quote_quantity_placeholder" => "Estimated quantity (in tons)",
  "company_placeholder" => "Your company name",
  "message_placeholder" => "Your message",
  "address_title" => "Our Address",
  "contact_button" => "Send Message",
  "quote_button" => "Request Quote",
  "name" => "Name",
  "email" => "Email",
  "message" => "Message",
  "company" => "Company",
  "product" => "Product",
  "quantity" => "Quantity (tons)",
  "terms" => "Terms & Conditions",
  "privacy" => "Privacy Policy",
  "address" => "Jl. Mampang Prapatan Raya No.73A Lantai 3, Desa/Kelurahan Tegal Parang, 12790",
  "phone" => "+62 8785700800872",
  "email_contact" => "archipelagojayanusantara@gmail.com"
];
